# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Playpost' do
  inherit! :search_paths
  pod 'AppCenter/Crashes', '~> 2.0.1'
  pod 'AppCenter/Analytics', '~> 2.0.1'
  pod 'AppCenterReactNativeShared', '~> 2.0.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Playpost



  # pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  # pod 'RNKeychain', :path => '../node_modules/react-native-keychain'

  # pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  # pod 'RNFS', :path => '../node_modules/react-native-fs'

  # pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  # pod 'react-native-video', :path => '../node_modules/react-native-video'

  # pod 'react-native-async-storage', :path => '../node_modules/@react-native-community/async-storage'

  # pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  # pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  # pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  # pod 'RNIap', :path => '../node_modules/react-native-iap'

  # pod 'react-native-config', :path => '../node_modules/react-native-config'

  # pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  target 'PlaypostShareExtension' do
    inherit! :complete
  end

  target 'PlaypostTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
